export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export default function RootLayout({ children }) {
  
  return (
    <html lang="ru">
      <body>
          {children}
          <Toaster duration={5000} richColors/>
      </body>
    </html>
  )
}
