import { Geist, Geist_Mono } from "next/font/google";
import { Sidebar, SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { Separator } from '@radix-ui/react-dropdown-menu';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from '@/components/ui/breadcrumb';
import { Button } from '@/components/ui/button';
import { Toaster } from "@/components/ui/sonner";
import { DataProvider } from "../components/DataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <DataProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <div className="p-4">
                {children}
              </div>
            </SidebarInset>
          </SidebarProvider>
          {/* <CheckAuthDashboard/> */}
        </DataProvider>
        
  );
}
